services:
  - type: web
    name: cometai-server
    env: python
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "python server.py"
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: 1
